project:
  type: book
  output-dir: docs

book:
  title: "Data Science for Political Science"
  date: "September 2022"
  chapters:
    - index.qmd
    - intro.qmd
    - 02-Description.qmd
    - 03-CausalityI.qmd
  number_sections: true
  number-depth: 4
  page-navigation: true
  sidebar:
    style: docked
    background: light
    foreground: darkred

format:
  html:
    theme: yeti
    toc-title: Section Contents
    toc: true
    toc-location: left
    toc-depth: 4
    linkcolor: red
  


editor: visual

