project:
  type: book
  output-dir: docs

book:
  title: "Data Science for Political Science"
  date: "September 2022"
  chapters:
    - index.qmd
    - intro.qmd
    - 02-Description.qmd
  number-depth: 4


format:
  html:
    theme: United
  pdf:
    documentclass: scrreprt

editor: visual

